"""Make a clean, public copy of MonoSpace (no git history, no personal or course material).

    python tools/export_public.py <empty target folder>

Copies the files git tracks, minus the private ones below, writes a fresh CHANGELOG.md and an
empty MODULES.md, then scans the copy for personal markers and course material and stops
(exit 1) if anything is found. It never touches DATA_DIR and never deletes anything: the
target folder must not exist yet, or must be empty. Then `git init` + commit there yourself.
"""
from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Private: personal instructions, migration history, the original Claude.ai build, course text.
EXCLUDE_PREFIXES = (
    ".claude/", "CLAUDE.md", "CHANGELOG.md", "MODULES.md", "legacy/",
    "docs/PLAN.md", "docs/DATA-MIGRATION.md", "docs/SETUP-GUIDE.md",
    "tests/fixtures/module2-text.json", "tests/fixtures/module3-text.json",
    "tests/golden/module2.expected.json", "tests/golden/module3.expected.json",
)

# Anything matching these in the copy stops the export. Author credit in LICENSE is fine.
MARKERS = re.compile(
    r"elisha|yang\.elishalee|@gmail\.com|\bElish\b|DrillData|OneDrive\\|ITCS318|S-ITCS|"
    r"mui02dwojkee|muaicdxx9pud|mujpsn2zi373|mstob7djkylq|information assurance|"
    r"sk-ant-[A-Za-z0-9]|GOCSPX-|AIza[0-9A-Za-z_-]{20}", re.I)
MARKER_EXEMPT = {"LICENSE", "app/vendor/pdfjs/pdf.worker.min.js", "app/vendor/pdfjs/pdf.min.js",
                 "tools/export_public.py", "tools/check_secrets.py",
                 "tests/server/test_check_secrets.py"}

CHANGELOG = """# CHANGELOG

Newest first.

## 1.0.0 — first public release

- MonoSpace: a local, offline-first study app. Builds decks from lecture slides and notes;
  spaced-repetition review, multiple choice, typed answers, flashcards, a study guide, test
  papers and an AI teacher.
- Local server (FastAPI + SQLite) with automatic snapshots; nothing leaves your PC except the
  AI requests you make.
- AI: Claude through the official Claude Code program when online, Qwen through Ollama
  offline. No API keys.
- Module library: re-uploading the same PDF opens its deck; a revised PDF lists what changed.
- MIT licence.
"""

MODULES = """# MODULES

Generated by the MonoSpace server (`server/modules.py`) after every module upload. Do not edit
by hand. Empty until you upload your first module.
"""


def tracked() -> list[str]:
    out = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True)
    return [line for line in out.stdout.splitlines() if line]


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    target = Path(sys.argv[1]).resolve()
    if target == ROOT or ROOT in target.parents:
        print("The target must be outside this repository.")
        return 2
    if target.exists() and any(target.iterdir()):
        print(f"{target} is not empty. Choose a new or empty folder (nothing is deleted).")
        return 2
    target.mkdir(parents=True, exist_ok=True)

    copied = skipped = 0
    for rel in tracked():
        if rel.startswith(EXCLUDE_PREFIXES):
            skipped += 1
            continue
        src, dst = ROOT / rel, target / rel
        if not src.is_file():
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        copied += 1
    (target / "CHANGELOG.md").write_text(CHANGELOG, encoding="utf-8", newline="\n")
    (target / "MODULES.md").write_text(MODULES, encoding="utf-8", newline="\n")
    print(f"Copied {copied} files, left out {skipped} private files -> {target}")

    hits = []
    for f in sorted(target.rglob("*")):
        rel = f.relative_to(target).as_posix()
        if not f.is_file() or rel in MARKER_EXEMPT or rel.startswith(".git/"):
            continue
        try:
            text = f.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for n, line in enumerate(text.splitlines(), 1):
            m = MARKERS.search(line)
            if m:
                hits.append(f"  {rel}:{n}: {m.group(0)!r}")
    if hits:
        print("STOP: personal or course markers found in the public copy:")
        print("\n".join(hits[:50]))
        return 1
    print("Scan: no personal markers, course material or secrets found.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
